name: mira
description: "A privacy-focused browser built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.12.0
  flutter_inappwebview: ^6.1.5
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.3.3
  lottie: ^3.1.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  showcaseview: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/1.json
    - assets/2.json
    - assets/3.json
    - assets/icon.png

flutter_native_splash:
  color: "#000000"
  
  android_12:
    color: "#000000"
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
