name: mira
description: "A privacy-focused browser built with Flutter."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.12.0
  flutter_inappwebview: ^6.1.5
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  lottie: ^3.1.0 
  smooth_page_indicator: ^1.1.0
  showcaseview: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/1.json
    - assets/2.json
    - assets/3.json